# fly.toml file generated for ratethedub on 2021-05-03T17:43:12-04:00

app = "ratethedub"

kill_signal = "SIGTERM"
kill_timeout = 5

[env]

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s" # allow some time for startup
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

  [[services.http_checks]]
    grace_period = "30s" # allow some time for startup
    interval = "60s"
    restart_limit = 6
    timeout = "2s"
    method = "get"
    path = "/en/"
    protocol = "https"
    tls_skip_verify = false
