# Taken and adapted from
# https://medium.com/@gottfrois/github-actions-for-elixir-phoenix-app-with-cache-6ca33f628459

# TODO at later dates
# - Update Ubuntu to latest

name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MIX_ENV: test

jobs:
  deps:
    name: Dependencies
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        elixir: [1.12]
        otp: [24.0]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
          mix dialyzer --plt
          MIX_ENV=dev mix dialyzer --plt

  ### --- ###

  static_code_analysis:
    name: Static Code Analysis
    needs: deps
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        elixir: [1.11]
        otp: [23.2]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Fake Prettier Installation
        run: |
          mkdir -p ./assets/node_modules/.bin/
          cp /bin/true ./assets/node_modules/.bin/prettier

      - name: Check Code Format
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo -i todo

      - name: Run Dialyzer
        run: MIX_ENV=dev mix dialyzer --no-check --halt-exit-status

  ### --- ###

  unit_tests:
    name: Unit Tests
    needs: deps
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        elixir: [1.11]
        otp: [23.2]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Setup Database
        run: mix do ecto.create, ecto.migrate

      - name: Run test
        run: mix test --trace --slowest 10
